apiVersion: v2
name: eip-controller
description: Per-pod Elastic IP lifecycle controller for EKS scraper workloads
type: application
version: 0.1.3
appVersion: "0.1.0"
keywords:
  - kubernetes
  - aws
  - eip
  - controller
  - networking
  - eks
home: https://github.com/ronakforcast/eip-controller-helm
sources:
  - https://github.com/ronakforcast/eip-controller-helm
maintainers:
  - name: ronakforcast
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    - kind: added
      description: Initial release
    - kind: changed
      description: Set image to ghcr.io/ronakforcast/eip-controller:0.1.0
