apiVersion: v1
kind: Service
metadata:
  name: {{ include "eip-controller.name" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eip-controller.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: eip-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: health
      port: 8081
      targetPort: 8081
      protocol: TCP
